// User reducer types
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
export const SET_USER = 'SET_USER';
export const LOADING_USER = 'LOADING_USER';
export const MARK_NOTIFICATIONS_READ = 'MARK_NOTIFICATIONS_READ';
// UI reducer types
export const SET_ERRORS = 'SET_ERRORS';
export const LOADING_UI = 'LOADING_UI';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const LOADING_DATA = 'LOADING_DATA';
export const STOP_LOADING_UI = 'STOP_LOADING_UI';
// Data reducer types
export const SET_SCREAMS = 'SET_SCREAMS';
export const SET_TOP_REVIEWS = 'SET_TOP_REVIEWS';
export const SET_BUSINESS = 'SET_BUSINESS';
export const SET_COMPARE_BUSINESSES = 'SET_COMPARE_BUSINESSES';
export const SET_BUSINESSES = 'SET_BUSINESSES';
export const SET_SCREAM = 'SET_SCREAM';
export const SET_REVIEWS = 'SET_REVIEWS';
export const SET_ALL_BUSINESS = 'SET_ALL_BUSINESS';
export const SET_BLOG_POST = 'SET_BLOG_POST';
export const SET_SINGLE_POST = 'SET_SINGLE_POST';
export const SET_VIDEOS = 'SET_VIDEOS';
export const SET_FIVESTAR_REVIEWS = 'SET_FIVESTAR_REVIEWS';
export const SET_FOURSTAR_REVIEWS = 'SET_FOURSTAR_REVIEWS';
export const LIKE_SCREAM = 'LIKE_SCREAM';
export const UNLIKE_SCREAM = 'UNLIKE_SCREAM';
export const DELETE_SCREAM = 'DELETE_SCREAM';
export const POST_SCREAM = 'POST_SCREAM';
export const SUBMIT_COMMENT = 'SUBMIT_COMMENT';
export const SET_CANCELMEMBERSHIP = 'SET_CANCELMEMBERSHIP';
export const FOLLOW = 'FOLLOW';
export const SET_SEARCH_VALUE = 'SET_SEARCH_VALUE';
export const UN_FOLLOW = 'UN_FOLLOW';
export const SET_PASSWORD_RESET = 'SET_PASSWORD_RESET';
export const CREATE_REVIEW = 'CREATE_REVIEW';
export const SET_OVERAL_RATING = 'SET_OVERAL_RATING';
