import React, {Component} from 'react';
import AboutSvg from "../contents/AboutSVG";
import '../style/desktop/about.scss';
import '../style/mobile/aboutMob.scss';
import security from '../images/ai/Group 818@2x.png'
import transparentReview from '../images/transparentRev.png'
import saveMoney from '../images/ai/Group 814@2x.png'
import reliable from '../images/reliable.png'

class About extends Component {
    render() {
        return (
            <div className="aboutPage">
                <AboutSvg/>

                <div className="aboutWrap">


                <div className="aboutCont">

                    <div className="title2">
                        <h1>What is the purpose of ChecknCommit?</h1>
                    </div>

                    <p>
                        Our Mission: To Be the Most Trusted Review Platform in the World
                    </p>
                    <section className="title2">
                       <h2> What is ChecknCommit®?</h2>
                    </section>

                    <section>
                        <p> ChecknCommit® is an online community of reviewers that benefits businesses and consumers
                            by sharing honest and genuine feedback on selling and purchasing experiences.
                        </p>
                        <p> ChecknCommit® is not just for business, it allows consumers to review businesses and
                            organizations such as restaurants, schools, network providers, churches and other companies.
                        </p>
                        <p> ChecknCommit® was founded in 2019 with the goal of passing on our experience, so that people
                            do not fall foul of unscrupulous businesses. We want to achieve this goal through a
                            completely
                            transparent and unbiased platform.

                        </p>
                    </section>

                    <section className="imgTxt">

                        <div className="txt">
                            <h2>Transparent and unbiased</h2>
                            <p>
                               No review can be deleted.
                            </p>
                        </div>

                        <div className="img">
                            <img src={transparentReview} alt=""/>
                        </div>
                    </section>

                    <section>
                        <p> We are committed to helping businesses collate reviews and work with their customers to
                            overcome any issues arising from their experiences. Ultimately, this will help the business
                            improve its service and should leave the customer feeling more valued.
                        </p>
                        <p> We also want to provide consumers with a means to learn more about the businesses they
                            engage with. This will give them confidence to commit to purchasing their goods and services
                        </p>

                    </section>


                    <section className="imgTxt">

                        <div className="txt">
                            <h1>Save Money</h1>
                            <p>
                                By choosing the
                                right business
                                you save money.
                            </p>
                        </div>

                        <div className="img">
                            <img src={saveMoney} alt=""/>
                        </div>
                    </section>


                    <div className="title2">
                        <h2>How Feedback Creates Transparency</h2>
                    </div>


                    <section>
                        <p> ChecknCommit® hosted reviews are generated by users who are part of our online community.
                            These reviews are open and accessible to anyone that wants to view them.
                        </p>
                            <p> Our belief in letting people share their transaction experiences improves transparency;
                                enhances trust; and ultimately forges better relationships between consumers and
                                Business.
                            </p>
                            <p>
                                When businesses engage positively with the feedback (whether it be good, bad or
                                indifferent) they prove to their customers that they matter to them and are valued.
                                This, in turn, is paid back through improved customer loyalty.


                            </p>


                    </section>


                    <section className="imgTxt">

                        <div className="txt">
                            <h1>RELIABLE</h1>
                            <p>
                                All reviews are
                                100% authentic from
                                real users
                            </p>
                        </div>

                        <div className="img">
                            <img src={reliable} alt=""/>
                        </div>
                    </section>

                </div>

                </div>
            </div>
    );
    }
    }

    export default About;